import unittest

from meta_updater.shared.text import (
    excerpt_html,
    render_text,
    sanitize_html,
    sanitize_unicode,
)


class TextRenderingTests(unittest.TestCase):
    def test_unicode_sanitizer_removes_zero_width_controls_and_noncharacters(self) -> None:
        self.assertEqual(
            sanitize_unicode("A\u200bB\ufeffC\x00D\ufdd0E\nF"),
            "ABCDE\nF",
        )

    def test_single_outer_paragraph_is_removed(self) -> None:
        rendered = render_text("A short package description.")
        self.assertEqual(rendered.body_html, "A short package description.")

    def test_multiple_paragraphs_keep_structural_tags(self) -> None:
        rendered = render_text("First paragraph.\n\nSecond paragraph.")
        self.assertEqual(
            rendered.body_html,
            "<p>First paragraph.</p><p>Second paragraph.</p>",
        )

    def test_raw_html_is_escaped(self) -> None:
        rendered = render_text("<script>alert(1)</script> **safe**")
        self.assertNotIn("<script>", rendered.body_html)
        self.assertIn("&lt;script&gt;", rendered.body_html)

    def test_declared_html_is_sanitized_and_unwrapped(self) -> None:
        rendered = render_text(
            '<p>Hello <strong>world</strong><script>bad()</script>.</p>',
            media_type="text/html",
        )
        self.assertEqual(rendered.body_html, "Hello <strong>world</strong>.")

    def test_plain_declared_markdown_is_detected(self) -> None:
        rendered = render_text(
            "# Package\n\nA **useful** description.", media_type="text/plain"
        )
        self.assertEqual(
            rendered.body_html,
            "A <strong>useful</strong> description.",
        )

    def test_sanitizer_rejects_unsafe_links_and_images(self) -> None:
        self.assertEqual(
            sanitize_html(
                '<a href="javascript:bad()">bad</a>'
                '<a href="https://example.test">good</a><img src="tracking">'
            ),
            '<a>bad</a><a href="https://example.test">good</a>',
        )

    def test_summary_is_bounded(self) -> None:
        rendered = render_text("word " * 100, summary_limit=40)
        self.assertTrue(rendered.truncated)
        self.assertLessEqual(len(rendered.summary_text), 41)

    def test_body_is_bounded_before_rendering(self) -> None:
        rendered = render_text("word " * 100, body_limit=40)
        self.assertTrue(rendered.truncated)
        self.assertLess(len(rendered.body_html), 80)

    def test_body_keeps_only_two_source_blocks(self) -> None:
        rendered = render_text(
            "First.\n\nSecond.\n\nThird.",
            block_limit=2,
        )
        self.assertEqual(
            rendered.body_html,
            "<p>First.</p><p>Second.</p>",
        )
        self.assertTrue(rendered.truncated)

    def test_html_excerpt_skips_headings_and_preserves_two_prose_blocks(self) -> None:
        rendered = excerpt_html(
            "<h1>Package</h1><p>Useful description.</p><p>Unneeded details.</p>"
        )
        self.assertEqual(
            rendered.body_html,
            "<p>Useful description.</p><p>Unneeded details.</p>",
        )

    def test_html_excerpt_drops_comments_and_placeholder_headings(self) -> None:
        rendered = excerpt_html(
            "<p>&lt;!--- THIS FILE IS AUTOMATICALLY GENERATED ---&gt;</p>"
            "<p>stb ===</p>"
        )
        self.assertEqual(rendered.body_html, "")

    def test_html_excerpt_finds_prose_after_readme_furniture(self) -> None:
        rendered = excerpt_html(
            "<p># Package</p><p>[![CI](badge.svg)](ci.example)</p>"
            "<p>A useful package description.</p>"
        )
        self.assertEqual(rendered.body_html, "A useful package description.")

    def test_html_excerpt_drops_reference_images_and_escaped_html(self) -> None:
        rendered = excerpt_html(
            "<p>![banner][project_banner]</p>"
            "<p>&lt;a href=\"https://example.test\"&gt;Useful **prose**.&lt;/a&gt;</p>"
        )
        self.assertEqual(rendered.body_html, "Useful <strong>prose</strong>.")

    def test_html_excerpt_repairs_loose_markdown_emphasis(self) -> None:
        rendered = excerpt_html("<p>** Useful description. **</p>")
        self.assertEqual(
            rendered.body_html, "<strong>Useful description.</strong>"
        )


if __name__ == "__main__":
    unittest.main()
