name: C++ Social
repo: cppsocial/site
description: Your primary resource for C++ communities, events, blogs, and more
topics:
  - cpp
  - communities
  - events
  - resources
  - static-site
  - hugo
