- id: barrys_cpp_blog
  title: Barry's C++ Blog
  author: Barry Revzin
  website_url: https://brevzin.github.io/
  rss_url: https://brevzin.github.io/feed.xml
- id: cpp_stories
  title: C++ Stories
  author: Bartłomiej Filipek
  website_url: https://www.cppstories.com/
  rss_url: https://www.cppstories.com/index.xml
