- id: modernes_cpp
  title: Modernes C++
  author: Rainer Grimm and contributors
  website_url: https://www.modernescpp.com/
  rss_url: https://www.modernescpp.com/index.php/feed/
  sitemap_url: https://www.modernescpp.com/wp-sitemap-posts-post-1.xml
