name: Update Metadata Weekly

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        updater:
          - blogs
          - books
          - communities
          - events
          - packages
          - youtube
    uses: ./.github/workflows/update-metadata.yaml
    with:
      updater: ${{ matrix.updater }}
